version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ../data/redis:/data
    networks:
      - app_net
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    privileged: true
    ports:
      - 80:80
    volumes:
      - ../data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../data/nginx/log:/var/log/nginx
      - ../data/nginx/dist:/usr/share/nginx/dist
    networks:
      - app_net

  demo:
    image: demo:latest
    container_name: demo
    restart: always
    networks:
      - app_net
    ports:
      - 8080:8080
    depends_on:
      - redis

networks:
  app_net:
    external: false